project:
  type: website

website:
  title: "Bowen de Gouw"
  site-url: https://bdegouw.github.io/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: professionalsummary.qmd
        text: Professional Summary
      - href: projects.qmd
        text: Projects
      - href: certifications.qmd
        text: Certifications
      - href: blog.qmd
        text: Blog
      - href: favorites.qmd
        text: Favorites
      - href: contact.qmd
        text: Contact Me
search: false
page-navigation: true

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



