project:
  type: website

website:
  title: "Bowen de Gouw"
  site-url: https://bdegouw.github.io/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: professionalsummary.qmd
        text: Professional Summary
      - href: additional.qmd
        text: Projects
      - href: contact.qmd
        text: Contact Me


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



