project:
  type: website

website:
  title: "Bowen de Gouw"
  favicon: bdglogo.png
  site-url: "https://bdegouw.github.io/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: professionalsummary.qmd
        text: Professional Summary
      - text: Academics
        menu:
          - text: Course Overview
            href: classes.qmd
          - text: Example 1
            href: example1drop.qmd
      - href: certifications.qmd
        text: Certifications
      - href: blog.qmd
        text: Blog
      - href: contact.qmd
        text: Contact Me
  search: false
  page-navigation: true

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
